name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si estás usando otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Usa la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/<Delirios>  # Reemplaza <nombre-del-proyecto> con el nombre de tu proyecto
